### ISSUE TITLE
Support for schema references 

### ISSUE THREAD

**Issue by williamboxhall** [avro-kotlin/avro4k#120]
Avro supports creating a union type of [schema references](https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/), which reference other separate independently evolving schema files for each element of the union type. Is this something Avro4k might support in the future?

**Comment by thake** [comment]
@williamboxhall thanks for raising this question. As far as I can tell, schema references are a part of the Confluent schema registry spec. I don't think support for schema references should be included in Avro4k. But maybe I'm just lacking a little bit of imagination :)
Can you specify how avro4k could help handle schema references for Confluent schema registry?

**Comment by GreyTeardrop** [comment]
I've looked more into the code, and it seems like Avro's native `SchemaBuilder` does not support referencing other schemas. The schema I've posted above can be parsed, but when dumped, it would embed the nested object instead of referencing it, so there's probably no easy way to dump schemas that refer to other schemas.

**Comment by thake** [comment]
@GreyTeardrop thanks for pointing out a case of native schema referencing in avro! I haven't been aware of that.

Do you have a specific use case for avro4k in mind where this could be useful? Again, it seems I'm lacking some imagination :innocent:

**Comment by GreyTeardrop** [comment]
The thought was to keep Kotlin models as a source of Avro schemas, but generate JSON schemas for clients that can't directly consume Kotlin models. Ideally to make those JSON schemas easier readable not only for software but also for developers, they might reference included sub-schemas instead of nesting them.

This isn't a really strong usecase - it's perfectly possible to live with dumping schemas the way they are right now.

**Comment by thake** [comment]
@GreyTeardrop, thanks for your input on the use case. This seems to be a totally valid use case if you chose the code-first approach to managing schemas. 

I did some research on this matter in the Avro bug archives. It seems like the Avro team concisely decided not to include schema referencing into Avro schemas. The Avro team favored a pre-processor approach instead (see https://issues.apache.org/jira/browse/AVRO-1188?focusedCommentId=13490809&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13490809).

As there is no native Avro support for explicitly referencing schemas, I wouldn't want to include native support for schema separation in avro4k. You can, however, write up some post-processing that splits the resulting schema into multiple files. It should be an easy task. I think one could develop a little open source library that only depends on the Avro library. Would be cool to see it.
