### ISSUE TITLE
Instant Serialization is Lossy

### ISSUE THREAD

**Issue by royaldark** [avro-kotlin/avro4k#70]
The `InstantSerializer` does not preserve the nanosecond portion of the value, leading to lossy round-trip serialization. I discovered this by accident when switching to a new computer, which apparently supports nanosecond-precision timestamps via `Instant.now()`.

To reproduce:

```kt
@Serializable
data class Holder(
  @Serializable(with = InstantSerializer::class)
  val value: Instant
)

val input = Holder(Instant.now().plusNanos(177))
val serialized = Avro.default.encodeToByteArray(Holder.serializer(), input)
val deserialized = Avro.default.decodeFromByteArray(Holder.serializer(), serialized)

println(input)
println(deserialized)
```

prints

```
Holder(value=2020-09-12T23:01:16.606000177Z)
Holder(value=2020-09-12T23:01:16.606Z)
```

**Comment by thake** [comment]
@royaldark Thanks for taking the time to raise this issue.

The current InstantSerializer implementation corresponds to the logical type [timestamp-millis](https://avro.apache.org/docs/current/spec.html#Local+timestamp+%28millisecond+precision%29). A new InstantToMicroSerializer needs to be implemented to also support [timestamp-micros](https://avro.apache.org/docs/current/spec.html#Timestamp+%28microsecond+precision%29). Would you be interested in providing a PR that adds this new Serializer?

However you would still lose the nanosecond precision. If you need nanosecond precision you'll have to implement your own serializer, because the logical type timestamp-nanos does not exist in the avro specification.
